# Generated by Django 5.1 on 2024-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebigkasAPP', '0005_alter_room_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
