# Generated by Django 5.1 on 2024-09-02 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebigkasAPP', '0007_recentcalls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentcalls',
            name='duration',
            field=models.DurationField(default=datetime.timedelta, null=True),
        ),
        migrations.AlterField(
            model_name='recentcalls',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
