# Generated by Django 5.1 on 2024-09-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebigkasAPP', '0011_alter_recentcalls_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='recentcalls',
            name='status',
            field=models.CharField(default='missed', max_length=10, null=True),
        ),
    ]
