# Generated by Django 5.1 on 2024-09-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebigkasAPP', '0012_remove_room_status_recentcalls_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recentcalls',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
