# Generated by Django 5.1 on 2024-09-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebigkasAPP', '0013_room_status_alter_recentcalls_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentcalls',
            name='status',
            field=models.CharField(default='missed', max_length=10, null=True),
        ),
    ]
