# Generated by Django 5.1 on 2024-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebigkasAPP', '0014_alter_recentcalls_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
