# Generated by Django 5.1.1 on 2024-09-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebigkasLearnings', '0002_seed_learnings_with_model_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='description',
        ),
        migrations.AddField(
            model_name='learning',
            name='action_model',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learning',
            name='model_file_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learning',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='UserLearning',
        ),
    ]
