# Generated by Django 5.1.1 on 2024-09-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebigkasAdminAPP', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['created_at']},
        ),
    ]
