# Generated by Django 5.0.1 on 2024-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newUser',
            field=models.BooleanField(default=True),
        ),
    ]
