# Generated by Django 5.0.1 on 2024-07-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userprofile_newuser'),
        ('base', '0005_userprofile_status'),
    ]

    operations = [
    ]
